class RangeFilter:
    """
        RangeFilter(dist_range)

        Define a range filter to reduce noise in the scans generated by a LIDAR sensor.
        Range filter crops all the values that are below and above the RANGE_MIN and RANGE_MAX
        and replaces them with RANGE_MIN and RANGE_MAX respectively.

        Parameters
        ----------
        dist_range : tuple
                     Tuple specifying the min and max values of measured distances by LIDAR sensor
    """

    def __init__(self, dist_range=(0.03, 50)):
        self.RANGE_MIN = dist_range[0]
        self.RANGE_MAX = dist_range[1]

    def update(self, x):
        """
        Filter values of a LIDAR scan by stripping the extremes values greater or lesser
        than the max or min ranges with the max or min values respectively

        Parameters
        ----------
        x : array_like
            Updates of a LIDAR sensor scan

        Returns
        -------
        filtered scan : LIDAR scan with values adjusted to be within the pre-specified range
        """
        x = x[:]
        for i in range(len(x)):
            if x[i] < self.RANGE_MIN:
                x[i] = self.RANGE_MIN
            elif x[i] > self.RANGE_MAX:
                x[i] = self.RANGE_MAX
        return x
